name: flutter_sms_inbox
description: Flutter plugin to easily query device SMS Inbox. Supports android only.
homepage: https://github.com/jgithaiga/flutter_sms_inbox
version: 0.1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.juliusgithaiga.flutter_sms_inbox
    pluginClass: FlutterSmsInboxPlugin
